### PR TITLE
Updates to privacy practices

### PR DESCRIPTION
**Pull request by sankarshanmukhopadhyay**
WIP - please do not merge PR

### CODE REVIEW

**Comment by amarts** [comment]
Meaningful change! I like putting it up at the top!

**Comment by sankarshanmukhopadhyay** [comment]
The summary section has been expanded in the privacy controls and data use sections.

**Review by amarts — APPROVED** [review]
I still see WIP in title, hence not yet merging.

@smohan-dw good if you have a look once.

**Comment by sankarshanmukhopadhyay** [comment]
> I still see WIP in title, hence not yet merging.

Fixed that one :)

**Comment by smohan-dw** [comment]
looks good to merge

**Pull request merged**
